### PR TITLE
Converted the README to markdown merged from the google code wiki

### PR DESCRIPTION
**Pull request by penguinpowernz**
This seems much nicer to me.  A single pretty file from which to get all the information you need to install and operate skippy-xd.

### CODE REVIEW

**Comment by landroni** [comment]
Looks good to me. 

@richardgv Any remarks before I merge?

**Comment by penguinpowernz** [comment]
Looks like @richardgv is AWOL, should go ahead and merge - it's only a README.  It will help users of the software right?

**Comment by mouarfff** [comment]
Hello,

I'm on linux mint mate 18.3 and i'm using http://ppa.launchpad.net/landronimirc/skippy-xd-daily/ubuntu repository, and i couple this with brightside-propertie to initate skippy-xd with mouse on a corner.

So there is a strange behavior : when I move mouse on the corner, it's ok, skippy-xd launch but the mouse go to center of the screen, and I must clic once before reclic to a windows to take it. It's impossible to take front the window with the first clic.
And, with placement mouse problem, it become very strange and not intuitive, so i don't use it to increase productivity has  I used it on other desktop.
Another problem is each time you move the mouse on the corner, each time skippy-xd initiate, and you have to clic on the screen same number of time you move the mouse on the corner.

I'm using skippy-xd to replace "expose" function but with this strange behavior i't impossible to have realy smouth usage.

Is there anything to do to solve this issues ?

**Comment by penguinpowernz** [comment]
@mouarfff you may want to open a new issue.

**Comment by penguinpowernz** [comment]
No one cares, clearly.

**Pull request closed without merging**
